name: Release
on:
  workflow_dispatch

jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
      - name: Install Dependencies
        run: npm i && npm ci && yarn
      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_TOKEN: ${{ secrets.NPM_TOKEN }}
          token: ${{ secrets.NPM_TOKEN }}
        run: |
          npm config set registry https://registry.npmjs.org/
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          npm owner add rmalakar shareimage
