name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install Dependencies and Authenticate
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm i
      - name: Start CI
        run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn pack
          yarn publish *.tgz
          npm depreciate "Due to security and other issues, this package will be published (v1 API WON'T be re-published) with the new name @formpod/shareimage"
