name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install Dependencies
        run: npm i && npm ci && yarn
      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_TOKEN: ${{ secrets.NPM_TOKEN }}
          token: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          npm deprecate shareimage ""
          yarn publish --access public
          npm deprecate shareimage "Due to security and other issues, this package will be published (v1 API WON'T be re-published) with the new name @formpod/shareimage"
