name: Release
on:
  workflow_dispatch:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install Dependencies
        run: npm i
      - name: Start CI
        run: npm ci
      - name: Do pre-packing
        run: |
          npm run build
          cp package.json dist/
          cp CHANGELOG.md dist/
          cp LICENSE dist/
          cp README.md dist/
          cp -r assets dist/assets
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release --branches main
